### ISSUE TITLE
postgres和mysql，插入一条数据，返回数据结构不一样

### ISSUE THREAD

**Issue by jiangwei1995** [DaYeSquad/sakura-node-ts#23]
describe("Test buildInsertQuery 返回主键id", () => {
    it("InsertQuery 返回主键id", () => {
      let user: User = new User();
      user.initAsNewUser(111, "pig", "jiangwei", `{"a":"hello","b":"world"}`, 188821212, new Date(1));
      const query: InsertQuery = new InsertQuery().fromModel(user);
      const result: QueryResult = DBClient.getClient().query(query);
      chai.expect(result[0]["uid"]).to.exist; // postgres
      chai.expect(result[0]["insertId"]).to.exist; // mysql
    });
  });

**Comment by lovelypeople** [comment]
在 3.0.8 中修复了
