### ISSUE TITLE
Pg数据库的表名需要加引号

### ISSUE THREAD

**Issue by ipv4sec** [DaYeSquad/sakura-node-ts#32]
在Pg数据库中, 如果数据库名为 user, 构建出来的SQL语句是 `SELECT * FROM user` , 但是Pg里面user是系统表

![1](https://user-images.githubusercontent.com/29883657/30839954-448f18a4-a2a7-11e7-8ece-74c2d62676df.png)

ORM构建的SQL语句应该是 `SELECT * FROM "user"`

![qq](https://user-images.githubusercontent.com/29883657/30840028-9abefdf2-a2a7-11e7-80f1-eb1a9413cf5e.png)

辛苦 : )

**Comment by lovelypeople** [comment]
用 users 吧，或者 `"user"`，不要用保留字来建表...
