### ISSUE TITLE
在 pgquerybuilder.ts#L411 中定义了字段类型，在 pgquerybuilder.ts#L411 中的valueAsStringByType没有判断导致控制台大量输出SqlType is 8, value is xx

### ISSUE THREAD

**Issue by Shonke** [DaYeSquad/sakura-node-ts#33]
在 [pgquerybuilder.ts#L411](https://github.com/DaYeSquad/sakura-node-ts/blob/master/src/database/postgres/pgquerybuilder.ts#L411) 中定义了字段类型，在 [pgquerybuilder.ts#L411](https://github.com/DaYeSquad/sakura-node-ts/blob/master/src/database/postgres/pgquerybuilder.ts#L411) 中的`valueAsStringByType`没有判断导致控制台大量输出`SqlType is 8, value is xx`

**Comment by lovelypeople** [comment]
在 3.2.0 中解决了
